useDatabase: true
migrateData: false
implicitHomeName: __home__
mysql:
  schemaVersion: 1
  credentials:
    host: localhost
    username: user
    password: password
    port: 3306
    database: database