useDatabase: false
migrateData: false
implicitHomeName: __home__
listImplicitHome: false
mysql:
  schemaVersion: 1
  credentials:
    host: localhost
    username: user
    password: password
    port: 3306
    database: database
uuidRegex: '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[34][0-9a-fA-F]{3}-[89ab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}j'